# Use the official Node.js image as base
FROM node:18

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY server/package*.json ./server/

# Change working directory to the server directory
WORKDIR /usr/src/app/server

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY server .

# Expose the port your app runs on
EXPOSE 3000

# Command to run your app using npm
CMD ["node", "server.js"]
